### ISSUE TITLE
Cases with wrong weak_warning StatusCode

### ISSUE THREAD

**Issue by Magellanth** [Petschko/dhl-php-sdk#62]
Case 1
When i try to create a international label (suisse) without the needed additional Information i get a StatusCode DHL_ERROR_WEAK_WARNING but the StatusMessage is "Hard validation error.;Bitte geben Sie die Art der Sendung an." so shouldnt this get a DHL_ERROR_HARD_VAL_ERROR?

Case 2
I got a DHL_ERROR_WEAK_WARNING  with StatusMessage "login failed;Der Nutzer des Webservice konnte nicht identifiziert werden."
Shouldnt this be DHL_ERROR_AUTH_FAILED?

Case 3
I got DHL_ERROR_WEAK_WARNING with StatusMessage "ok;Der Webservice wurde ohne Fehler ausgeführt." (with some Break or Tab in it)
This should be DHL_ERROR_NO_ERROR

In Response Class line 320:
`if($this->getStatusCode() === 0 && $this->getStatusText() !== 'ok')`

You could use something like
`if($this->getStatusCode() === 0 && ($this->getStatusText() !== 'ok' 
||  preg_replace('/\s+/', ' ', $this->getStatusText() === "ok;Der Webservice wurde ohne Fehler ausgeführt.")))`

Maybe easier:
`strpos($this->getStatusText(),"ok") !== 0` but i dont know if this would collide with any other messages that could start with "ok"

**Comment by Petschko** [comment]
It would probably help.

But I think it would help me to find the issue here, when you send me the XML-Requests, you did were all that happend, you can do it with `$dhl->getLastXML()` AFTER the request(s)

Please note, when you have multiple requests at the same time you need to give the key of the Shipment you want to know, else it uses the first shipment by default:
https://github.com/Petschko/dhl-php-sdk/blob/master/examples/getting-started.md#petschkodhlresponse-object
