### ISSUE TITLE
SECURITY_VIOLATION

### ISSUE THREAD

**Issue by trebaxa** [Petschko/dhl-php-sdk#77]
Hello guys,

we switched now to live enviroment and entered the coreckt credentials.
But when we want to get a new lable, we got this error back: SECURITY_VIOLATION
The application has been approved by DHL.

Any hint?

`Petschko\DHL\Credentials Object
(
    [user:Petschko\DHL\Credentials:private] => XXX-sports
    [signature:Petschko\DHL\Credentials:private] => XXXXXXX!
    [ekp:Petschko\DHL\Credentials:private] => 631XXXX6820101
    [apiUser:Petschko\DHL\Credentials:private] => XXXXiondhl_1
    [apiPassword:Petschko\DHL\Credentials:private] => ZHSuXXXXXXXXX4Bj8DKEr
)`

**Comment by Petschko** [comment]
I can imagine that the problem is because you probably need to use the Version 3 of their API, while this Project only supports API v. 2

DHL wrote, that new customer **have to** use 3.x, while version 2 can still used a long time until support runs out (but only old customers).

I already wrote the mayor part of the update to version 3, just I don't get a tiny last part to work, thats why I still dont have a stable v3 release.

You can use the dev branch to get the API-Version 3 compatibility, but its not fully documented yet

**Comment by commeco** [comment]
If you open a ticket inside of the dhl portal and ask for 2.x compatibility and if you say that you still worked on an application, the support is very accommodating and switch you to the "old" version. That was our experience.

**Comment by trebaxa** [comment]
THX. They switched us back to version 2. Now it works. Hope version 3 is ready soon! God job guys!

**Comment by Petschko** [comment]
Awesome! That's good to hear ^^
