### ISSUE TITLE
Encoding: object has no 'ShipmentOrder' property

### ISSUE THREAD

**Issue by mpitz** [Petschko/dhl-php-sdk#82]
Hi,

in first place I got an error with the dev-master version saying: 
`Array
(
    [0] => SECURITY_VIOLATION
)`

So i read https://github.com/Petschko/dhl-php-sdk/issues/64#issuecomment-600298840 and installed the petschko/dhl-php-sdk:dev-dev
After that I got (with the same credentials) this error:
`Array
(
    [0] => SOAP-ERROR: Encoding: object has no 'ShipmentOrder' property
)`
Maybe therefore: https://github.com/Petschko/dhl-php-sdk/issues/64#issuecomment-615859975

The DHL Business Account is brand new, so I guess I have to use version 3 of the API.
The App is activated, and also ALL services are activated, so I retrieved an AppID and an App-Token.

When testing with sandbox credentials in the dev-master version everything was fine.

What to do?

**Comment by Petschko** [comment]
I think the best way to find out whats the issue is when you send that code here or to me via E-Mail. Some error-messages of DHL are not that self explanatory

Yes you are right, you have to use the Dev-Branch when your DHL-Account is new (then you use Version 3), so the issue must be something different

**Comment by Petschko** [comment]
Bump to see if this is still relevant
